#!/usr/bin/env Rscript
suppressMessages({ library(chromote); library(callr) })
PROJ <- "/usrfiles/shared-projects/users/kaiping_yang/shinyAssistantUI"; PORT <- 8993
proc <- callr::r_bg(function(proj, port) {
  setwd(proj); suppressMessages(library(shiny))
  shiny::runApp("tests/verify/sources_image_app.R", host="127.0.0.1", port=port, launch.browser=FALSE)
}, args=list(proj=PROJ, port=PORT), stdout="/tmp/si.log", stderr="/tmp/si.err")
on.exit({ try(proc$kill(), silent=TRUE) }, add=TRUE)
Sys.sleep(9); if (!proc$is_alive()) { cat(readLines("/tmp/si.err"), sep="\n"); quit(status=1) }
b <- ChromoteSession$new(); b$Page$navigate(sprintf("http://127.0.0.1:%d/", PORT)); b$Page$loadEventFired(); Sys.sleep(4)
ev <- function(js) tryCatch(b$Runtime$evaluate(js)$result$value, error=function(e) NA)
chk <- function(n,c,d="") cat(sprintf("[%s] %-26s %s\n", if(isTRUE(c))"PASS" else "FAIL", n, d))
ev("document.querySelector('[contenteditable=true]').focus()"); Sys.sleep(0.5)
b$Input$insertText(text = "answer please")
Sys.sleep(0.5)
b$Input$dispatchKeyEvent(type="keyDown", key="Enter", code="Enter", windowsVirtualKeyCode=13L)
b$Input$dispatchKeyEvent(type="keyUp", key="Enter", code="Enter", windowsVirtualKeyCode=13L)
Sys.sleep(3)
n_src <- ev("document.querySelectorAll('.aui-source-cite').length")
chk("source_parts_rendered", as.integer(n_src) >= 2, sprintf("(count=%s)", n_src))
src_txt <- ev("(function(){return Array.from(document.querySelectorAll('.aui-source-cite')).map(e=>e.innerText).join(' | ')})()")
cat("sources:", src_txt, "\n")
chk("source_titles_shown", grepl("Reference Paper", src_txt) && grepl("Wikipedia", src_txt), "")
n_img <- ev("document.querySelectorAll('img.aui-message-image').length")
chk("image_part_rendered", as.integer(n_img) >= 1, sprintf("(imgs=%s)", n_img))
img_src_ok <- ev("(function(){var i=document.querySelector('img.aui-message-image');return i?i.src.indexOf('data:image/png')===0:false})()")
chk("image_src_datauri", isTRUE(img_src_ok), "")
b$close(); proc$kill(); system("rm -f /tmp/si.log /tmp/si.err")
cat("DONE\n")
